server:
  port: 8080
  servlet:
    context-path: /indentity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/a_devteria"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "4708fbaa9ac3b09928e72e34717313e5ed4875ccbcda39a9ea764b0835ce2657"