server:
  port: 8080
  servlet:
    context-path: /indentity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/a_devteria"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true